// Copyright 2021 Google LLC
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: secops_log.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NEXT TAG: 6
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw data for the log entry.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Timestamp of the log entry if not self contained.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The time at which the log entry was collected.
	CollectionTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collection_time,json=collectionTime,proto3" json:"collection_time,omitempty"`
	// Location for the log entry, given as the name of a file in the IANA time
	// zone database. This is used to determine the offset from UTC for the log
	// entry. If not supplied, times in the log entry are assumed to be UTC.
	// Ex: "America/New_York"
	// See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
	Timezone string `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// Source info for this log entry, if not present batch source is effective.
	// This allows logs within a batch to be from multiple sources.
	Source        *EventSource `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_secops_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_secops_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_secops_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetCollectionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectionTime
	}
	return nil
}

func (x *LogEntry) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *LogEntry) GetSource() *EventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

// NEXT TAG: 10
type LogEntryBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source information.
	Source *EventSource `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Log type in string.
	LogType string `protobuf:"bytes,9,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	// Opaque hint to help parsing the log.
	Hint string `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	// Log entries in this batch.
	Entries []*LogEntry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	// Timestamp the collector started.
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryBatch) Reset() {
	*x = LogEntryBatch{}
	mi := &file_secops_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryBatch) ProtoMessage() {}

func (x *LogEntryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_secops_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryBatch.ProtoReflect.Descriptor instead.
func (*LogEntryBatch) Descriptor() ([]byte, []int) {
	return file_secops_log_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntryBatch) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LogEntryBatch) GetSource() *EventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LogEntryBatch) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *LogEntryBatch) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *LogEntryBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogEntryBatch) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

var File_secops_log_proto protoreflect.FileDescriptor

const file_secops_log_proto_rawDesc = "" +
	"\n" +
	"\x10secops_log.proto\x12\x19googlesecops.ingestion.v2\x1a\x13secops_source.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12C\n" +
	"\x0fcollection_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecollectionTime\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12>\n" +
	"\x06source\x18\x04 \x01(\v2&.googlesecops.ingestion.v2.EventSourceR\x06source\"\x88\x02\n" +
	"\rLogEntryBatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12>\n" +
	"\x06source\x18\x02 \x01(\v2&.googlesecops.ingestion.v2.EventSourceR\x06source\x12\x19\n" +
	"\blog_type\x18\t \x01(\tR\alogType\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\x12=\n" +
	"\aentries\x18\x05 \x03(\v2#.googlesecops.ingestion.v2.LogEntryR\aentries\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTimeBdZbgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlesecopsexporter/protos/apib\x06proto3"

var (
	file_secops_log_proto_rawDescOnce sync.Once
	file_secops_log_proto_rawDescData []byte
)

func file_secops_log_proto_rawDescGZIP() []byte {
	file_secops_log_proto_rawDescOnce.Do(func() {
		file_secops_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secops_log_proto_rawDesc), len(file_secops_log_proto_rawDesc)))
	})
	return file_secops_log_proto_rawDescData
}

var file_secops_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_secops_log_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: googlesecops.ingestion.v2.LogEntry
	(*LogEntryBatch)(nil),         // 1: googlesecops.ingestion.v2.LogEntryBatch
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*EventSource)(nil),           // 3: googlesecops.ingestion.v2.EventSource
}
var file_secops_log_proto_depIdxs = []int32{
	2, // 0: googlesecops.ingestion.v2.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: googlesecops.ingestion.v2.LogEntry.collection_time:type_name -> google.protobuf.Timestamp
	3, // 2: googlesecops.ingestion.v2.LogEntry.source:type_name -> googlesecops.ingestion.v2.EventSource
	3, // 3: googlesecops.ingestion.v2.LogEntryBatch.source:type_name -> googlesecops.ingestion.v2.EventSource
	0, // 4: googlesecops.ingestion.v2.LogEntryBatch.entries:type_name -> googlesecops.ingestion.v2.LogEntry
	2, // 5: googlesecops.ingestion.v2.LogEntryBatch.start_time:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_secops_log_proto_init() }
func file_secops_log_proto_init() {
	if File_secops_log_proto != nil {
		return
	}
	file_secops_source_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secops_log_proto_rawDesc), len(file_secops_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secops_log_proto_goTypes,
		DependencyIndexes: file_secops_log_proto_depIdxs,
		MessageInfos:      file_secops_log_proto_msgTypes,
	}.Build()
	File_secops_log_proto = out.File
	file_secops_log_proto_goTypes = nil
	file_secops_log_proto_depIdxs = nil
}
