// Copyright 2021 Google LLC
//
// Whenever the proto fields are changed here the same change should be copied
// to the Chronicle Server side proto definition

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: secops_stats.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stats about the collection agent.
// NEXT TAG: 11
type AgentStatsEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp when the collector started.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Time the stats below were last reset. (Event timestamp is window_end)
	// This corresponds to the last stats upload that was successful.
	WindowStartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=window_start_time,json=windowStartTime,proto3" json:"window_start_time,omitempty"`
	// Timestamp of the last successful batch upload.
	LastSuccessfulUploadTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_successful_upload_time,json=lastSuccessfulUploadTime,proto3" json:"last_successful_upload_time,omitempty"`
	// The unique id of the agent
	AgentId []byte `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Stats about the receivers.
	ReceiverStats []*ReceiverStats `protobuf:"bytes,5,rep,name=receiver_stats,json=receiverStats,proto3" json:"receiver_stats,omitempty"`
	// Stats about the processors.
	ProcessorStats []*ProcessorStats `protobuf:"bytes,6,rep,name=processor_stats,json=processorStats,proto3" json:"processor_stats,omitempty"`
	// Stats about the exporters.
	ExporterStats []*ExporterStats `protobuf:"bytes,7,rep,name=exporter_stats,json=exporterStats,proto3" json:"exporter_stats,omitempty"`
	// CPU time spent on the process.
	ProcessCpuSeconds int64 `protobuf:"varint,8,opt,name=process_cpu_seconds,json=processCpuSeconds,proto3" json:"process_cpu_seconds,omitempty"`
	// Memory in kilobytes occupied by the process.
	ProcessMemoryRss int64 `protobuf:"varint,9,opt,name=process_memory_rss,json=processMemoryRss,proto3" json:"process_memory_rss,omitempty"`
	// Number of seconds from which the process is running.
	ProcessUptime int64 `protobuf:"varint,10,opt,name=process_uptime,json=processUptime,proto3" json:"process_uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatsEvent) Reset() {
	*x = AgentStatsEvent{}
	mi := &file_secops_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatsEvent) ProtoMessage() {}

func (x *AgentStatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatsEvent.ProtoReflect.Descriptor instead.
func (*AgentStatsEvent) Descriptor() ([]byte, []int) {
	return file_secops_stats_proto_rawDescGZIP(), []int{0}
}

func (x *AgentStatsEvent) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *AgentStatsEvent) GetWindowStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStartTime
	}
	return nil
}

func (x *AgentStatsEvent) GetLastSuccessfulUploadTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessfulUploadTime
	}
	return nil
}

func (x *AgentStatsEvent) GetAgentId() []byte {
	if x != nil {
		return x.AgentId
	}
	return nil
}

func (x *AgentStatsEvent) GetReceiverStats() []*ReceiverStats {
	if x != nil {
		return x.ReceiverStats
	}
	return nil
}

func (x *AgentStatsEvent) GetProcessorStats() []*ProcessorStats {
	if x != nil {
		return x.ProcessorStats
	}
	return nil
}

func (x *AgentStatsEvent) GetExporterStats() []*ExporterStats {
	if x != nil {
		return x.ExporterStats
	}
	return nil
}

func (x *AgentStatsEvent) GetProcessCpuSeconds() int64 {
	if x != nil {
		return x.ProcessCpuSeconds
	}
	return 0
}

func (x *AgentStatsEvent) GetProcessMemoryRss() int64 {
	if x != nil {
		return x.ProcessMemoryRss
	}
	return 0
}

func (x *AgentStatsEvent) GetProcessUptime() int64 {
	if x != nil {
		return x.ProcessUptime
	}
	return 0
}

// Stats about the receiver.
// NEXT TAG: 4
type ReceiverStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the receiver.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Number of logs received.
	AcceptedSpans int64 `protobuf:"varint,2,opt,name=accepted_spans,json=acceptedSpans,proto3" json:"accepted_spans,omitempty"`
	// Number of logs dropped.
	RefusedSpans  int64 `protobuf:"varint,3,opt,name=refused_spans,json=refusedSpans,proto3" json:"refused_spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiverStats) Reset() {
	*x = ReceiverStats{}
	mi := &file_secops_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiverStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiverStats) ProtoMessage() {}

func (x *ReceiverStats) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiverStats.ProtoReflect.Descriptor instead.
func (*ReceiverStats) Descriptor() ([]byte, []int) {
	return file_secops_stats_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiverStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReceiverStats) GetAcceptedSpans() int64 {
	if x != nil {
		return x.AcceptedSpans
	}
	return 0
}

func (x *ReceiverStats) GetRefusedSpans() int64 {
	if x != nil {
		return x.RefusedSpans
	}
	return 0
}

// Stats about the processor.
// NEXT TAG: 4
type ProcessorStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the processor.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Number of logs processed.
	AcceptedSpans int64 `protobuf:"varint,2,opt,name=accepted_spans,json=acceptedSpans,proto3" json:"accepted_spans,omitempty"`
	// number of logs dropped.
	RefusedSpans  int64 `protobuf:"varint,3,opt,name=refused_spans,json=refusedSpans,proto3" json:"refused_spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorStats) Reset() {
	*x = ProcessorStats{}
	mi := &file_secops_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorStats) ProtoMessage() {}

func (x *ProcessorStats) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorStats.ProtoReflect.Descriptor instead.
func (*ProcessorStats) Descriptor() ([]byte, []int) {
	return file_secops_stats_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessorStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessorStats) GetAcceptedSpans() int64 {
	if x != nil {
		return x.AcceptedSpans
	}
	return 0
}

func (x *ProcessorStats) GetRefusedSpans() int64 {
	if x != nil {
		return x.RefusedSpans
	}
	return 0
}

// Stats about the exporter.
// NEXT TAG: 6
type ExporterStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the exporter.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Number of logs sent.
	AcceptedSpans int64 `protobuf:"varint,2,opt,name=accepted_spans,json=acceptedSpans,proto3" json:"accepted_spans,omitempty"`
	// Number of logs dropped.
	RefusedSpans int64 `protobuf:"varint,3,opt,name=refused_spans,json=refusedSpans,proto3" json:"refused_spans,omitempty"`
	// Capacity of the queue.
	QueueCapacity int64 `protobuf:"varint,4,opt,name=queue_capacity,json=queueCapacity,proto3" json:"queue_capacity,omitempty"`
	// Current size of the queue.
	QueueSize     int64 `protobuf:"varint,5,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExporterStats) Reset() {
	*x = ExporterStats{}
	mi := &file_secops_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExporterStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporterStats) ProtoMessage() {}

func (x *ExporterStats) ProtoReflect() protoreflect.Message {
	mi := &file_secops_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporterStats.ProtoReflect.Descriptor instead.
func (*ExporterStats) Descriptor() ([]byte, []int) {
	return file_secops_stats_proto_rawDescGZIP(), []int{3}
}

func (x *ExporterStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExporterStats) GetAcceptedSpans() int64 {
	if x != nil {
		return x.AcceptedSpans
	}
	return 0
}

func (x *ExporterStats) GetRefusedSpans() int64 {
	if x != nil {
		return x.RefusedSpans
	}
	return 0
}

func (x *ExporterStats) GetQueueCapacity() int64 {
	if x != nil {
		return x.QueueCapacity
	}
	return 0
}

func (x *ExporterStats) GetQueueSize() int64 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

var File_secops_stats_proto protoreflect.FileDescriptor

const file_secops_stats_proto_rawDesc = "" +
	"\n" +
	"\x12secops_stats.proto\x12\x19googlesecops.ingestion.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x05\n" +
	"\x0fAgentStatsEvent\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12F\n" +
	"\x11window_start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fwindowStartTime\x12Y\n" +
	"\x1blast_successful_upload_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x18lastSuccessfulUploadTime\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\fR\aagentId\x12O\n" +
	"\x0ereceiver_stats\x18\x05 \x03(\v2(.googlesecops.ingestion.v2.ReceiverStatsR\rreceiverStats\x12R\n" +
	"\x0fprocessor_stats\x18\x06 \x03(\v2).googlesecops.ingestion.v2.ProcessorStatsR\x0eprocessorStats\x12O\n" +
	"\x0eexporter_stats\x18\a \x03(\v2(.googlesecops.ingestion.v2.ExporterStatsR\rexporterStats\x12.\n" +
	"\x13process_cpu_seconds\x18\b \x01(\x03R\x11processCpuSeconds\x12,\n" +
	"\x12process_memory_rss\x18\t \x01(\x03R\x10processMemoryRss\x12%\n" +
	"\x0eprocess_uptime\x18\n" +
	" \x01(\x03R\rprocessUptime\"o\n" +
	"\rReceiverStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eaccepted_spans\x18\x02 \x01(\x03R\racceptedSpans\x12#\n" +
	"\rrefused_spans\x18\x03 \x01(\x03R\frefusedSpans\"p\n" +
	"\x0eProcessorStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eaccepted_spans\x18\x02 \x01(\x03R\racceptedSpans\x12#\n" +
	"\rrefused_spans\x18\x03 \x01(\x03R\frefusedSpans\"\xb5\x01\n" +
	"\rExporterStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eaccepted_spans\x18\x02 \x01(\x03R\racceptedSpans\x12#\n" +
	"\rrefused_spans\x18\x03 \x01(\x03R\frefusedSpans\x12%\n" +
	"\x0equeue_capacity\x18\x04 \x01(\x03R\rqueueCapacity\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x05 \x01(\x03R\tqueueSizeBdZbgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlesecopsexporter/protos/apib\x06proto3"

var (
	file_secops_stats_proto_rawDescOnce sync.Once
	file_secops_stats_proto_rawDescData []byte
)

func file_secops_stats_proto_rawDescGZIP() []byte {
	file_secops_stats_proto_rawDescOnce.Do(func() {
		file_secops_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secops_stats_proto_rawDesc), len(file_secops_stats_proto_rawDesc)))
	})
	return file_secops_stats_proto_rawDescData
}

var file_secops_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_secops_stats_proto_goTypes = []any{
	(*AgentStatsEvent)(nil),       // 0: googlesecops.ingestion.v2.AgentStatsEvent
	(*ReceiverStats)(nil),         // 1: googlesecops.ingestion.v2.ReceiverStats
	(*ProcessorStats)(nil),        // 2: googlesecops.ingestion.v2.ProcessorStats
	(*ExporterStats)(nil),         // 3: googlesecops.ingestion.v2.ExporterStats
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_secops_stats_proto_depIdxs = []int32{
	4, // 0: googlesecops.ingestion.v2.AgentStatsEvent.start_time:type_name -> google.protobuf.Timestamp
	4, // 1: googlesecops.ingestion.v2.AgentStatsEvent.window_start_time:type_name -> google.protobuf.Timestamp
	4, // 2: googlesecops.ingestion.v2.AgentStatsEvent.last_successful_upload_time:type_name -> google.protobuf.Timestamp
	1, // 3: googlesecops.ingestion.v2.AgentStatsEvent.receiver_stats:type_name -> googlesecops.ingestion.v2.ReceiverStats
	2, // 4: googlesecops.ingestion.v2.AgentStatsEvent.processor_stats:type_name -> googlesecops.ingestion.v2.ProcessorStats
	3, // 5: googlesecops.ingestion.v2.AgentStatsEvent.exporter_stats:type_name -> googlesecops.ingestion.v2.ExporterStats
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_secops_stats_proto_init() }
func file_secops_stats_proto_init() {
	if File_secops_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secops_stats_proto_rawDesc), len(file_secops_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secops_stats_proto_goTypes,
		DependencyIndexes: file_secops_stats_proto_depIdxs,
		MessageInfos:      file_secops_stats_proto_msgTypes,
	}.Build()
	File_secops_stats_proto = out.File
	file_secops_stats_proto_goTypes = nil
	file_secops_stats_proto_depIdxs = nil
}
