// Copyright 2021 Google LLC

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: secops_events.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event type common to all events in this batch.
type EventBatch_EventType int32

const (
	EventBatch_UNSPECIFIED EventBatch_EventType = 0
	EventBatch_AGENT_STATS EventBatch_EventType = 25
)

// Enum value maps for EventBatch_EventType.
var (
	EventBatch_EventType_name = map[int32]string{
		0:  "UNSPECIFIED",
		25: "AGENT_STATS",
	}
	EventBatch_EventType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"AGENT_STATS": 25,
	}
)

func (x EventBatch_EventType) Enum() *EventBatch_EventType {
	p := new(EventBatch_EventType)
	*p = x
	return p
}

func (x EventBatch_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventBatch_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_secops_events_proto_enumTypes[0].Descriptor()
}

func (EventBatch_EventType) Type() protoreflect.EnumType {
	return &file_secops_events_proto_enumTypes[0]
}

func (x EventBatch_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventBatch_EventType.Descriptor instead.
func (EventBatch_EventType) EnumDescriptor() ([]byte, []int) {
	return file_secops_events_proto_rawDescGZIP(), []int{1, 0}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time in microseconds at which this event took place (as opposed to
	// the time at which this event was ingested).
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The time in microseconds at which the event was collected.
	CollectionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=collection_time,json=collectionTime,proto3" json:"collection_time,omitempty"`
	// Payload carries event-specific information.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_AgentStats
	Payload isEvent_Payload `protobuf_oneof:"payload"`
	// Source info for this event, if not present batch source is effective.
	Source        *EventSource `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_secops_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_secops_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_secops_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetCollectionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectionTime
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetAgentStats() *AgentStatsEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_AgentStats); ok {
			return x.AgentStats
		}
	}
	return nil
}

func (x *Event) GetSource() *EventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_AgentStats struct {
	// Stats about the collection agent.
	AgentStats *AgentStatsEvent `protobuf:"bytes,24,opt,name=agent_stats,json=agentStats,proto3,oneof"`
}

func (*Event_AgentStats) isEvent_Payload() {}

// A batch of events.
type EventBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id (used to de-duplicate the batch).
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source info common to all events in this batch.
	Source *EventSource         `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Type   EventBatch_EventType `protobuf:"varint,3,opt,name=type,proto3,enum=googlesecops.ingestion.v2.EventBatch_EventType" json:"type,omitempty"`
	// The actual events.
	// A single batch should contain no more than 10,000 events.
	Events []*Event `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	// Timestamp the collector started.
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_secops_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_secops_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_secops_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventBatch) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *EventBatch) GetSource() *EventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *EventBatch) GetType() EventBatch_EventType {
	if x != nil {
		return x.Type
	}
	return EventBatch_UNSPECIFIED
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

var File_secops_events_proto protoreflect.FileDescriptor

const file_secops_events_proto_rawDesc = "" +
	"\n" +
	"\x13secops_events.proto\x12\x19googlesecops.ingestion.v2\x1a\x13secops_source.proto\x1a\x12secops_stats.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\x05Event\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12C\n" +
	"\x0fcollection_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecollectionTime\x12M\n" +
	"\vagent_stats\x18\x18 \x01(\v2*.googlesecops.ingestion.v2.AgentStatsEventH\x00R\n" +
	"agentStats\x12>\n" +
	"\x06source\x18\a \x01(\v2&.googlesecops.ingestion.v2.EventSourceR\x06sourceB\t\n" +
	"\apayload\"\xc5\x02\n" +
	"\n" +
	"EventBatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12>\n" +
	"\x06source\x18\x02 \x01(\v2&.googlesecops.ingestion.v2.EventSourceR\x06source\x12C\n" +
	"\x04type\x18\x03 \x01(\x0e2/.googlesecops.ingestion.v2.EventBatch.EventTypeR\x04type\x128\n" +
	"\x06events\x18\x04 \x03(\v2 .googlesecops.ingestion.v2.EventR\x06events\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"-\n" +
	"\tEventType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vAGENT_STATS\x10\x19BdZbgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlesecopsexporter/protos/apib\x06proto3"

var (
	file_secops_events_proto_rawDescOnce sync.Once
	file_secops_events_proto_rawDescData []byte
)

func file_secops_events_proto_rawDescGZIP() []byte {
	file_secops_events_proto_rawDescOnce.Do(func() {
		file_secops_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secops_events_proto_rawDesc), len(file_secops_events_proto_rawDesc)))
	})
	return file_secops_events_proto_rawDescData
}

var file_secops_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_secops_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_secops_events_proto_goTypes = []any{
	(EventBatch_EventType)(0),     // 0: googlesecops.ingestion.v2.EventBatch.EventType
	(*Event)(nil),                 // 1: googlesecops.ingestion.v2.Event
	(*EventBatch)(nil),            // 2: googlesecops.ingestion.v2.EventBatch
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*AgentStatsEvent)(nil),       // 4: googlesecops.ingestion.v2.AgentStatsEvent
	(*EventSource)(nil),           // 5: googlesecops.ingestion.v2.EventSource
}
var file_secops_events_proto_depIdxs = []int32{
	3, // 0: googlesecops.ingestion.v2.Event.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: googlesecops.ingestion.v2.Event.collection_time:type_name -> google.protobuf.Timestamp
	4, // 2: googlesecops.ingestion.v2.Event.agent_stats:type_name -> googlesecops.ingestion.v2.AgentStatsEvent
	5, // 3: googlesecops.ingestion.v2.Event.source:type_name -> googlesecops.ingestion.v2.EventSource
	5, // 4: googlesecops.ingestion.v2.EventBatch.source:type_name -> googlesecops.ingestion.v2.EventSource
	0, // 5: googlesecops.ingestion.v2.EventBatch.type:type_name -> googlesecops.ingestion.v2.EventBatch.EventType
	1, // 6: googlesecops.ingestion.v2.EventBatch.events:type_name -> googlesecops.ingestion.v2.Event
	3, // 7: googlesecops.ingestion.v2.EventBatch.start_time:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_secops_events_proto_init() }
func file_secops_events_proto_init() {
	if File_secops_events_proto != nil {
		return
	}
	file_secops_source_proto_init()
	file_secops_stats_proto_init()
	file_secops_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_AgentStats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secops_events_proto_rawDesc), len(file_secops_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secops_events_proto_goTypes,
		DependencyIndexes: file_secops_events_proto_depIdxs,
		EnumInfos:         file_secops_events_proto_enumTypes,
		MessageInfos:      file_secops_events_proto_msgTypes,
	}.Build()
	File_secops_events_proto = out.File
	file_secops_events_proto_goTypes = nil
	file_secops_events_proto_depIdxs = nil
}
