// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Request message for importing logs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: secops_http.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a telemetry log.
type Log struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of this log.
	// Format:
	// projects/{project}/locations/{region}/instances/{instance}/logTypes/{log_type}/logs
	// /{log}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Raw data for the log entry.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Timestamp of the log entry.
	LogEntryTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=log_entry_time,json=logEntryTime,proto3" json:"log_entry_time,omitempty"`
	// The time at which the log entry was collected. Must be after the
	// log_entry_time.
	CollectionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=collection_time,json=collectionTime,proto3" json:"collection_time,omitempty"`
	// The user-configured environment namespace to identify the data
	// domain the logs originated from. This namespace will be used as a tag to
	// identify the appropriate data domain for indexing and enrichment
	// functionality.
	EnvironmentNamespace string `protobuf:"bytes,5,opt,name=environment_namespace,json=environmentNamespace,proto3" json:"environment_namespace,omitempty"`
	// The user-configured custom metadata labels.
	Labels        map[string]*Log_LogLabel `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_secops_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_secops_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_secops_http_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetLogEntryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LogEntryTime
	}
	return nil
}

func (x *Log) GetCollectionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectionTime
	}
	return nil
}

func (x *Log) GetEnvironmentNamespace() string {
	if x != nil {
		return x.EnvironmentNamespace
	}
	return ""
}

func (x *Log) GetLabels() map[string]*Log_LogLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ImportLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent, which owns this collection of logs.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*ImportLogsRequest_InlineSource
	Source isImportLogsRequest_Source `protobuf_oneof:"source"`
	// Opaque hint to help parsing the log.
	Hint          string `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportLogsRequest) Reset() {
	*x = ImportLogsRequest{}
	mi := &file_secops_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLogsRequest) ProtoMessage() {}

func (x *ImportLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secops_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLogsRequest.ProtoReflect.Descriptor instead.
func (*ImportLogsRequest) Descriptor() ([]byte, []int) {
	return file_secops_http_proto_rawDescGZIP(), []int{1}
}

func (x *ImportLogsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ImportLogsRequest) GetSource() isImportLogsRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ImportLogsRequest) GetInlineSource() *ImportLogsRequest_LogsInlineSource {
	if x != nil {
		if x, ok := x.Source.(*ImportLogsRequest_InlineSource); ok {
			return x.InlineSource
		}
	}
	return nil
}

func (x *ImportLogsRequest) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type isImportLogsRequest_Source interface {
	isImportLogsRequest_Source()
}

type ImportLogsRequest_InlineSource struct {
	// Logs to be imported are specified inline.
	InlineSource *ImportLogsRequest_LogsInlineSource `protobuf:"bytes,2,opt,name=inline_source,json=inlineSource,proto3,oneof"`
}

func (*ImportLogsRequest_InlineSource) isImportLogsRequest_Source() {}

// Label for a user configured custom metadata key.
type Log_LogLabel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value of the label.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Indicates whether this label can be used for Data RBAC.
	RbacEnabled   bool `protobuf:"varint,2,opt,name=rbac_enabled,json=rbacEnabled,proto3" json:"rbac_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_LogLabel) Reset() {
	*x = Log_LogLabel{}
	mi := &file_secops_http_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_LogLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_LogLabel) ProtoMessage() {}

func (x *Log_LogLabel) ProtoReflect() protoreflect.Message {
	mi := &file_secops_http_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_LogLabel.ProtoReflect.Descriptor instead.
func (*Log_LogLabel) Descriptor() ([]byte, []int) {
	return file_secops_http_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Log_LogLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Log_LogLabel) GetRbacEnabled() bool {
	if x != nil {
		return x.RbacEnabled
	}
	return false
}

// A import source with the logs to import included inline.
type ImportLogsRequest_LogsInlineSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The logs being imported.
	Logs []*Log `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	// The forwarder sending this import request.
	Forwarder string `protobuf:"bytes,2,opt,name=forwarder,proto3" json:"forwarder,omitempty"`
	// Source file name. Populated for certain types of files processed by the
	// outofband processor which may have metadata encoded in it for use by
	// the parser.
	SourceFilename string `protobuf:"bytes,3,opt,name=source_filename,json=sourceFilename,proto3" json:"source_filename,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportLogsRequest_LogsInlineSource) Reset() {
	*x = ImportLogsRequest_LogsInlineSource{}
	mi := &file_secops_http_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportLogsRequest_LogsInlineSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportLogsRequest_LogsInlineSource) ProtoMessage() {}

func (x *ImportLogsRequest_LogsInlineSource) ProtoReflect() protoreflect.Message {
	mi := &file_secops_http_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportLogsRequest_LogsInlineSource.ProtoReflect.Descriptor instead.
func (*ImportLogsRequest_LogsInlineSource) Descriptor() ([]byte, []int) {
	return file_secops_http_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ImportLogsRequest_LogsInlineSource) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ImportLogsRequest_LogsInlineSource) GetForwarder() string {
	if x != nil {
		return x.Forwarder
	}
	return ""
}

func (x *ImportLogsRequest_LogsInlineSource) GetSourceFilename() string {
	if x != nil {
		return x.SourceFilename
	}
	return ""
}

var File_secops_http_proto protoreflect.FileDescriptor

const file_secops_http_proto_rawDesc = "" +
	"\n" +
	"\x11secops_http.proto\x12\x14googlesecops.http.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x03\n" +
	"\x03Log\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12@\n" +
	"\x0elog_entry_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flogEntryTime\x12C\n" +
	"\x0fcollection_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecollectionTime\x123\n" +
	"\x15environment_namespace\x18\x05 \x01(\tR\x14environmentNamespace\x12=\n" +
	"\x06labels\x18\x06 \x03(\v2%.googlesecops.http.v1.Log.LabelsEntryR\x06labels\x1a]\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".googlesecops.http.v1.Log.LogLabelR\x05value:\x028\x01\x1aC\n" +
	"\bLogLabel\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12!\n" +
	"\frbac_enabled\x18\x02 \x01(\bR\vrbacEnabled\"\xb5\x02\n" +
	"\x11ImportLogsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12_\n" +
	"\rinline_source\x18\x02 \x01(\v28.googlesecops.http.v1.ImportLogsRequest.LogsInlineSourceH\x00R\finlineSource\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\x1a\x88\x01\n" +
	"\x10LogsInlineSource\x12-\n" +
	"\x04logs\x18\x01 \x03(\v2\x19.googlesecops.http.v1.LogR\x04logs\x12\x1c\n" +
	"\tforwarder\x18\x02 \x01(\tR\tforwarder\x12'\n" +
	"\x0fsource_filename\x18\x03 \x01(\tR\x0esourceFilenameB\b\n" +
	"\x06sourceBdZbgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlesecopsexporter/protos/apib\x06proto3"

var (
	file_secops_http_proto_rawDescOnce sync.Once
	file_secops_http_proto_rawDescData []byte
)

func file_secops_http_proto_rawDescGZIP() []byte {
	file_secops_http_proto_rawDescOnce.Do(func() {
		file_secops_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secops_http_proto_rawDesc), len(file_secops_http_proto_rawDesc)))
	})
	return file_secops_http_proto_rawDescData
}

var file_secops_http_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_secops_http_proto_goTypes = []any{
	(*Log)(nil),               // 0: googlesecops.http.v1.Log
	(*ImportLogsRequest)(nil), // 1: googlesecops.http.v1.ImportLogsRequest
	nil,                       // 2: googlesecops.http.v1.Log.LabelsEntry
	(*Log_LogLabel)(nil),      // 3: googlesecops.http.v1.Log.LogLabel
	(*ImportLogsRequest_LogsInlineSource)(nil), // 4: googlesecops.http.v1.ImportLogsRequest.LogsInlineSource
	(*timestamppb.Timestamp)(nil),              // 5: google.protobuf.Timestamp
}
var file_secops_http_proto_depIdxs = []int32{
	5, // 0: googlesecops.http.v1.Log.log_entry_time:type_name -> google.protobuf.Timestamp
	5, // 1: googlesecops.http.v1.Log.collection_time:type_name -> google.protobuf.Timestamp
	2, // 2: googlesecops.http.v1.Log.labels:type_name -> googlesecops.http.v1.Log.LabelsEntry
	4, // 3: googlesecops.http.v1.ImportLogsRequest.inline_source:type_name -> googlesecops.http.v1.ImportLogsRequest.LogsInlineSource
	3, // 4: googlesecops.http.v1.Log.LabelsEntry.value:type_name -> googlesecops.http.v1.Log.LogLabel
	0, // 5: googlesecops.http.v1.ImportLogsRequest.LogsInlineSource.logs:type_name -> googlesecops.http.v1.Log
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_secops_http_proto_init() }
func file_secops_http_proto_init() {
	if File_secops_http_proto != nil {
		return
	}
	file_secops_http_proto_msgTypes[1].OneofWrappers = []any{
		(*ImportLogsRequest_InlineSource)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secops_http_proto_rawDesc), len(file_secops_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secops_http_proto_goTypes,
		DependencyIndexes: file_secops_http_proto_depIdxs,
		MessageInfos:      file_secops_http_proto_msgTypes,
	}.Build()
	File_secops_http_proto = out.File
	file_secops_http_proto_goTypes = nil
	file_secops_http_proto_depIdxs = nil
}
