// Copyright 2021 Google LLC

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: secops_source.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Information about the source collection point.
// In the future we can extend this message to include additional metadata
// such as location, division, subnet, etc.
type EventSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Customer GUID.
	CustomerId []byte `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Collector GUID.
	CollectorId []byte `protobuf:"bytes,2,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	// Source file name.
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	// The user-configured environment namespace to identify the data domain the
	// logs originated from. This namespace will be used as a tag to identify the
	// appropriate data domain for indexing and enrichment functionality.
	Namespace string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The user-configured custom metadata labels required by the customer
	Labels        []*Label `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSource) Reset() {
	*x = EventSource{}
	mi := &file_secops_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSource) ProtoMessage() {}

func (x *EventSource) ProtoReflect() protoreflect.Message {
	mi := &file_secops_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSource.ProtoReflect.Descriptor instead.
func (*EventSource) Descriptor() ([]byte, []int) {
	return file_secops_source_proto_rawDescGZIP(), []int{0}
}

func (x *EventSource) GetCustomerId() []byte {
	if x != nil {
		return x.CustomerId
	}
	return nil
}

func (x *EventSource) GetCollectorId() []byte {
	if x != nil {
		return x.CollectorId
	}
	return nil
}

func (x *EventSource) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EventSource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EventSource) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Key value labels.
type Label struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_secops_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_secops_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_secops_source_proto_rawDescGZIP(), []int{1}
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_secops_source_proto protoreflect.FileDescriptor

const file_secops_source_proto_rawDesc = "" +
	"\n" +
	"\x13secops_source.proto\x12\x19googlesecops.ingestion.v2\"\xc5\x01\n" +
	"\vEventSource\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\fR\n" +
	"customerId\x12!\n" +
	"\fcollector_id\x18\x02 \x01(\fR\vcollectorId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x128\n" +
	"\x06labels\x18\x05 \x03(\v2 .googlesecops.ingestion.v2.LabelR\x06labels\"/\n" +
	"\x05Label\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueBdZbgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlesecopsexporter/protos/apib\x06proto3"

var (
	file_secops_source_proto_rawDescOnce sync.Once
	file_secops_source_proto_rawDescData []byte
)

func file_secops_source_proto_rawDescGZIP() []byte {
	file_secops_source_proto_rawDescOnce.Do(func() {
		file_secops_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secops_source_proto_rawDesc), len(file_secops_source_proto_rawDesc)))
	})
	return file_secops_source_proto_rawDescData
}

var file_secops_source_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_secops_source_proto_goTypes = []any{
	(*EventSource)(nil), // 0: googlesecops.ingestion.v2.EventSource
	(*Label)(nil),       // 1: googlesecops.ingestion.v2.Label
}
var file_secops_source_proto_depIdxs = []int32{
	1, // 0: googlesecops.ingestion.v2.EventSource.labels:type_name -> googlesecops.ingestion.v2.Label
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_secops_source_proto_init() }
func file_secops_source_proto_init() {
	if File_secops_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secops_source_proto_rawDesc), len(file_secops_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secops_source_proto_goTypes,
		DependencyIndexes: file_secops_source_proto_depIdxs,
		MessageInfos:      file_secops_source_proto_msgTypes,
	}.Build()
	File_secops_source_proto = out.File
	file_secops_source_proto_goTypes = nil
	file_secops_source_proto_depIdxs = nil
}
