// Copyright 2021 Google LLC

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.4
// source: secops_ingestion.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchCreateEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *EventBatch            `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateEventsRequest) Reset() {
	*x = BatchCreateEventsRequest{}
	mi := &file_secops_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateEventsRequest) ProtoMessage() {}

func (x *BatchCreateEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secops_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateEventsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateEventsRequest) Descriptor() ([]byte, []int) {
	return file_secops_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *BatchCreateEventsRequest) GetBatch() *EventBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type BatchCreateEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateEventsResponse) Reset() {
	*x = BatchCreateEventsResponse{}
	mi := &file_secops_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateEventsResponse) ProtoMessage() {}

func (x *BatchCreateEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secops_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateEventsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateEventsResponse) Descriptor() ([]byte, []int) {
	return file_secops_ingestion_proto_rawDescGZIP(), []int{1}
}

type BatchCreateLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         *LogEntryBatch         `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateLogsRequest) Reset() {
	*x = BatchCreateLogsRequest{}
	mi := &file_secops_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateLogsRequest) ProtoMessage() {}

func (x *BatchCreateLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secops_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateLogsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateLogsRequest) Descriptor() ([]byte, []int) {
	return file_secops_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *BatchCreateLogsRequest) GetBatch() *LogEntryBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type BatchCreateLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateLogsResponse) Reset() {
	*x = BatchCreateLogsResponse{}
	mi := &file_secops_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateLogsResponse) ProtoMessage() {}

func (x *BatchCreateLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secops_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateLogsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreateLogsResponse) Descriptor() ([]byte, []int) {
	return file_secops_ingestion_proto_rawDescGZIP(), []int{3}
}

var File_secops_ingestion_proto protoreflect.FileDescriptor

const file_secops_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x16secops_ingestion.proto\x12\x19googlesecops.ingestion.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x13secops_events.proto\x1a\x10secops_log.proto\"W\n" +
	"\x18BatchCreateEventsRequest\x12;\n" +
	"\x05batch\x18\x01 \x01(\v2%.googlesecops.ingestion.v2.EventBatchR\x05batch\"\x1b\n" +
	"\x19BatchCreateEventsResponse\"X\n" +
	"\x16BatchCreateLogsRequest\x12>\n" +
	"\x05batch\x18\x01 \x01(\v2(.googlesecops.ingestion.v2.LogEntryBatchR\x05batch\"\x19\n" +
	"\x17BatchCreateLogsResponse2\xd4\x02\n" +
	"\x12IngestionServiceV2\x12\xa1\x01\n" +
	"\x11BatchCreateEvents\x123.googlesecops.ingestion.v2.BatchCreateEventsRequest\x1a4.googlesecops.ingestion.v2.BatchCreateEventsResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/events:batchCreate\x12\x99\x01\n" +
	"\x0fBatchCreateLogs\x121.googlesecops.ingestion.v2.BatchCreateLogsRequest\x1a2.googlesecops.ingestion.v2.BatchCreateLogsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v2/logs:batchCreateBdZbgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlesecopsexporter/protos/apib\x06proto3"

var (
	file_secops_ingestion_proto_rawDescOnce sync.Once
	file_secops_ingestion_proto_rawDescData []byte
)

func file_secops_ingestion_proto_rawDescGZIP() []byte {
	file_secops_ingestion_proto_rawDescOnce.Do(func() {
		file_secops_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secops_ingestion_proto_rawDesc), len(file_secops_ingestion_proto_rawDesc)))
	})
	return file_secops_ingestion_proto_rawDescData
}

var file_secops_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_secops_ingestion_proto_goTypes = []any{
	(*BatchCreateEventsRequest)(nil),  // 0: googlesecops.ingestion.v2.BatchCreateEventsRequest
	(*BatchCreateEventsResponse)(nil), // 1: googlesecops.ingestion.v2.BatchCreateEventsResponse
	(*BatchCreateLogsRequest)(nil),    // 2: googlesecops.ingestion.v2.BatchCreateLogsRequest
	(*BatchCreateLogsResponse)(nil),   // 3: googlesecops.ingestion.v2.BatchCreateLogsResponse
	(*EventBatch)(nil),                // 4: googlesecops.ingestion.v2.EventBatch
	(*LogEntryBatch)(nil),             // 5: googlesecops.ingestion.v2.LogEntryBatch
}
var file_secops_ingestion_proto_depIdxs = []int32{
	4, // 0: googlesecops.ingestion.v2.BatchCreateEventsRequest.batch:type_name -> googlesecops.ingestion.v2.EventBatch
	5, // 1: googlesecops.ingestion.v2.BatchCreateLogsRequest.batch:type_name -> googlesecops.ingestion.v2.LogEntryBatch
	0, // 2: googlesecops.ingestion.v2.IngestionServiceV2.BatchCreateEvents:input_type -> googlesecops.ingestion.v2.BatchCreateEventsRequest
	2, // 3: googlesecops.ingestion.v2.IngestionServiceV2.BatchCreateLogs:input_type -> googlesecops.ingestion.v2.BatchCreateLogsRequest
	1, // 4: googlesecops.ingestion.v2.IngestionServiceV2.BatchCreateEvents:output_type -> googlesecops.ingestion.v2.BatchCreateEventsResponse
	3, // 5: googlesecops.ingestion.v2.IngestionServiceV2.BatchCreateLogs:output_type -> googlesecops.ingestion.v2.BatchCreateLogsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_secops_ingestion_proto_init() }
func file_secops_ingestion_proto_init() {
	if File_secops_ingestion_proto != nil {
		return
	}
	file_secops_events_proto_init()
	file_secops_log_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secops_ingestion_proto_rawDesc), len(file_secops_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secops_ingestion_proto_goTypes,
		DependencyIndexes: file_secops_ingestion_proto_depIdxs,
		MessageInfos:      file_secops_ingestion_proto_msgTypes,
	}.Build()
	File_secops_ingestion_proto = out.File
	file_secops_ingestion_proto_goTypes = nil
	file_secops_ingestion_proto_depIdxs = nil
}
