receivers:
  nop:

processors:
  nop:

exporters:
  mezmo:
    ingest_url: "https://logs.logdna.com/log/ingest"
    ingest_key: "00000000000000000000000000000000"

service:
  pipelines:
    logs:
      receivers: [ nop ]
      processors: [ nop ]
      exporters: [ mezmo ]