FROM mysql:8.0.25

# Google wants us to install 'libmariadbclient18' for Debian 9 but mysql:8
# is based on Debian 10, which has libmariadb3
# https://cloud.google.com/monitoring/agent/plugins/mysql#debian-9
# https://mariadb.org/debian-10-mariadb-10-3/
ENV  MYSQL_DATABASE="otel"
ENV  MYSQL_USER="otel"
ENV  MYSQL_PASSWORD="otel"
ENV  MYSQL_ROOT_PASSWORD="otel"

RUN \
    apt-get update && \
    apt-get install -y libmariadb3