// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/config"
	"go.opentelemetry.io/collector/consumer/pdata"
)

// Type is the component type name.
const Type config.Type = "stubreceiver"

// MetricIntf is an interface to generically interact with generated metric.
type MetricIntf interface {
	Name() string
	New() pdata.Metric
	Init(metric pdata.Metric)
}

// Intentionally not exposing this so that it is opaque and can change freely.
type metricImpl struct {
	name     string
	initFunc func(pdata.Metric)
}

// Name returns the metric name.
func (m *metricImpl) Name() string {
	return m.name
}

// New creates a metric object preinitialized.
func (m *metricImpl) New() pdata.Metric {
	metric := pdata.NewMetric()
	m.Init(metric)
	return metric
}

// Init initializes the provided metric object.
func (m *metricImpl) Init(metric pdata.Metric) {
	m.initFunc(metric)
}

type metricStruct struct {
	StubBytes              MetricIntf
	StubCurrentConnections MetricIntf
	StubRequests           MetricIntf
	StubScoreboard         MetricIntf
	StubTraffic            MetricIntf
	StubUptime             MetricIntf
	StubWorkers            MetricIntf
}

// Names returns a list of all the metric name strings.
func (m *metricStruct) Names() []string {
	return []string{
		"stub.bytes",
		"stub.current_connections",
		"stub.requests",
		"stub.scoreboard",
		"stub.traffic",
		"stub.uptime",
		"stub.workers",
	}
}

var metricsByName = map[string]MetricIntf{
	"stub.bytes":               Metrics.StubBytes,
	"stub.current_connections": Metrics.StubCurrentConnections,
	"stub.requests":            Metrics.StubRequests,
	"stub.scoreboard":          Metrics.StubScoreboard,
	"stub.traffic":             Metrics.StubTraffic,
	"stub.uptime":              Metrics.StubUptime,
	"stub.workers":             Metrics.StubWorkers,
}

func (m *metricStruct) ByName(n string) MetricIntf {
	return metricsByName[n]
}

func (m *metricStruct) FactoriesByName() map[string]func(pdata.Metric) {
	return map[string]func(pdata.Metric){
		Metrics.StubBytes.Name():              Metrics.StubBytes.Init,
		Metrics.StubCurrentConnections.Name(): Metrics.StubCurrentConnections.Init,
		Metrics.StubRequests.Name():           Metrics.StubRequests.Init,
		Metrics.StubScoreboard.Name():         Metrics.StubScoreboard.Init,
		Metrics.StubTraffic.Name():            Metrics.StubTraffic.Init,
		Metrics.StubUptime.Name():             Metrics.StubUptime.Init,
		Metrics.StubWorkers.Name():            Metrics.StubWorkers.Init,
	}
}

// Metrics contains a set of methods for each metric that help with
// manipulating those metrics.
var Metrics = &metricStruct{
	&metricImpl{
		"stub.bytes",
		func(metric pdata.Metric) {
			metric.SetName("stub.bytes")
			metric.SetDescription("The number of bytes transferred by the HTTP server per second")
			metric.SetUnit("By")
			metric.SetDataType(pdata.MetricDataTypeDoubleGauge)
		},
	},
	&metricImpl{
		"stub.current_connections",
		func(metric pdata.Metric) {
			metric.SetName("stub.current_connections")
			metric.SetDescription("The number of active connections currently attached to the HTTP server")
			metric.SetUnit("connections")
			metric.SetDataType(pdata.MetricDataTypeIntGauge)
		},
	},
	&metricImpl{
		"stub.requests",
		func(metric pdata.Metric) {
			metric.SetName("stub.requests")
			metric.SetDescription("The number of requests serviced by the HTTP server per second")
			metric.SetUnit("/s")
			metric.SetDataType(pdata.MetricDataTypeDoubleGauge)
		},
	},
	&metricImpl{
		"stub.scoreboard",
		func(metric pdata.Metric) {
			metric.SetName("stub.scoreboard")
			metric.SetDescription("Apache HTTP server scoreboard values")
			metric.SetUnit("scoreboard")
			metric.SetDataType(pdata.MetricDataTypeIntGauge)
		},
	},
	&metricImpl{
		"stub.traffic",
		func(metric pdata.Metric) {
			metric.SetName("stub.traffic")
			metric.SetDescription("Total HTTP server traffic")
			metric.SetUnit("connections")
			metric.SetDataType(pdata.MetricDataTypeIntSum)
			metric.IntSum().SetIsMonotonic(true)
			metric.IntSum().SetAggregationTemporality(pdata.AggregationTemporalityCumulative)
		},
	},
	&metricImpl{
		"stub.uptime",
		func(metric pdata.Metric) {
			metric.SetName("stub.uptime")
			metric.SetDescription("The amount of time that the server has been running in seconds")
			metric.SetUnit("/s")
			metric.SetDataType(pdata.MetricDataTypeIntSum)
			metric.IntSum().SetIsMonotonic(true)
			metric.IntSum().SetAggregationTemporality(pdata.AggregationTemporalityCumulative)
		},
	},
	&metricImpl{
		"stub.workers",
		func(metric pdata.Metric) {
			metric.SetName("stub.workers")
			metric.SetDescription("The number of workers currently attached to the HTTP server")
			metric.SetUnit("connections")
			metric.SetDataType(pdata.MetricDataTypeIntGauge)
		},
	},
}

// M contains a set of methods for each metric that help with
// manipulating those metrics. M is an alias for Metrics
var M = Metrics

// Labels contains the possible metric labels that can be used.
var Labels = struct {
	// ScoreboardState (The state of a connection)
	ScoreboardState string
	// WorkersState (The state workers)
	WorkersState string
}{
	"state",
	"state",
}

// L contains the possible metric labels that can be used. L is an alias for
// Labels.
var L = Labels

// LabelScoreboardState are the possible values that the label "scoreboard_state" can have.
var LabelScoreboardState = struct {
	Open        string
	Waiting     string
	Starting    string
	Reading     string
	Sending     string
	Keepalive   string
	Dnslookup   string
	Closing     string
	Logging     string
	Finishing   string
	IdleCleanup string
}{
	"open",
	"waiting",
	"starting",
	"reading",
	"sending",
	"keepalive",
	"dnslookup",
	"closing",
	"logging",
	"finishing",
	"idle_cleanup",
}

// LabelWorkersState are the possible values that the label "workers_state" can have.
var LabelWorkersState = struct {
	Busy string
	Idle string
}{
	"busy",
	"idle",
}
