// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

const (
	Type      = "mongoatlasreceiver"
	Stability = component.StabilityLevelBeta
)
